### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by shawninder** [vigour-io/orientation#1]
Finish elaborating the api, which should allow listening for device orientation changes

**Comment by ninjatux** [comment]
from an old issue
- detect
- set
- lock
- unlock

**Comment by ninjatux** [comment]
## Orientation native specs

This plugin will be able to both manage and inform the application about device orientation change events.

#### Methods

###### `init`

Instantiate the plugin and fires the `change` event with the current orientation

###### `set(orientation)`

Will force the device to set a specific orientation and lock it. Argument is one of the following strings `landscape` or `portrait`.

###### `lock`

Will lock the device orientation to the current one

###### `unlock`

Remove the orientation lock

#### Events

The plugin must send and event on orientation change

###### `change(data)`

Fired on change of orientation passing the current orientation (`'landscape' || 'portrait'`) as data

###### `lock(data)`

Fired on lock passing the current lock status (`true || false`) as data

###### `ready(data)`

The ready event should be fired passing the current orientation, eg: `landscape` or `portrait`

## Orientation js specs

We can define the usage of this plugin to better understand the specs

``` js
var Orientation = require('vigour-orientation')

var or = new Orientation()
or.val = 'landscape' // calls 'set' on native and locks the orientation
or.locked.val = true // calls 'lock' on native

// we can then listen for changes
or.on(() => {
  if (this.val === 'landscape') console.log('Hey i\'m landscape')
  if (this.val === 'portrait') console.log('Hey i\'m portrait')
})
```

#### Properties

The JS plugin will have the `locked` property which will be automatically filled with a boolean value

**Comment by ninjatux** [comment]
@marcusbesjes can you review this?
