### ISSUE TITLE
upside-down portrait never allowed

### ISSUE THREAD

**Issue by shawninder** [vigour-io/orientation#11]
repro:
- `npm run ios-example`
- open workspace in xcode
- run in simulator (or on your device)
- rotate left (works)
- rotate left again, reaching the upside-down position
- EXPECT it to work again
- OBSERVE it doesn't work

**Comment by shawninder** [comment]
@avdwerff When I open the project in xcode, I can see that all the Device Orientations are selected, so I don't think there's anything wrong with the build script. Still, it doesn't work.. Can you check this out?

**Comment by avdwerff** [comment]
good one, I will check it.
